# Generated by Django 3.1.1 on 2021-01-29 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, unique=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['coordinates'], name='location_lo_coordin_69daf3_idx'),
        ),
    ]
